name: Deploy Portfolio to Oracle Cloud

on:
  push:
    branches:
      - main  # para ejecutar en la rama de main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to Server via SSH/SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./*"
        target: "/var/www/html/"
        strip_components: 0

    - name: Fix Permissions on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo chmod -R 755 /var/www/html
          sudo chown -R ubuntu:ubuntu /var/www/html